version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    user: app
    volumes:
      - .:/app
    command: dev
    links:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=True
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_LOG_FORMAT=json
  db:
    image: postgres:9.5@sha256:888b62ebb1265a7df59258fa22227e707faa2b39d9abfe2a1d6f9e3cd5936468
